### ISSUE TITLE
No contact info?

### ISSUE THREAD

**Issue by tmnsky** [shaqian/Not-Hotdog#1]
Looking to get in touch with you for a commercial implementation of this. If available, please contact me: tmnsky@gmail.com

Cheers

**Comment by jordanmcadoo** [comment]
Hi! I also came looking for contact info, but hoping to use this and fork it for a local presentation on Flutter.

**Comment by shaqian** [comment]
Hi,

My email address is x_ash@qq.com. Sorry I'm currently unavailable to work on commercial projects. Feel free to use/fork the source code and let me know if you encounter any issues.

Thanks,
Qian

**Comment by shaqian** [comment]
Archiving the issue for now. Feel free to reopen if you have other questions.
